// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/agent.proto
//
// Protocol Buffer definitions for the Golden Agent Policy Engine.

package agentpb

import (
	"encoding/json"
	"fmt"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// ExecutionStatus indicates the outcome of a tool execution request.
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_SUCCESS     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_DENIED      ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_ERROR       ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_INVALID     ExecutionStatus = 4
)

func (x ExecutionStatus) String() string {
	switch x {
	case ExecutionStatus_EXECUTION_STATUS_SUCCESS:
		return "SUCCESS"
	case ExecutionStatus_EXECUTION_STATUS_DENIED:
		return "DENIED"
	case ExecutionStatus_EXECUTION_STATUS_ERROR:
		return "ERROR"
	case ExecutionStatus_EXECUTION_STATUS_INVALID:
		return "INVALID"
	default:
		return "UNSPECIFIED"
	}
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return nil
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return nil
}


// RequestMetadata contains identity and context from the agent.
type RequestMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AgentType is the type/class of agent (e.g., "coding-assistant").
	AgentType string `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`

	// SandboxId identifies the specific sandbox instance.
	SandboxId string `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`

	// TenantId identifies the tenant for multi-tenant isolation.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`

	// SessionId identifies the agent session.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`

	// MtsLabel is the Multi-Tenant Security label (SHA-256 hash).
	MtsLabel string `protobuf:"bytes,5,opt,name=mts_label,json=mtsLabel,proto3" json:"mts_label,omitempty"`

	// Labels contains additional metadata as key-value pairs.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
}

func (x *RequestMetadata) String() string {
	return fmt.Sprintf("RequestMetadata{AgentType:%q, SandboxId:%q, TenantId:%q}", x.AgentType, x.SandboxId, x.TenantId)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *RequestMetadata) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RequestMetadata) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RequestMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestMetadata) GetMtsLabel() string {
	if x != nil {
		return x.MtsLabel
	}
	return ""
}

func (x *RequestMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ExecuteRequest represents a tool execution request from an agent.
type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ToolName is the name of the tool to execute.
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`

	// Parameters contains tool-specific parameters as JSON-encoded bytes.
	Parameters []byte `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`

	// Metadata contains agent identity and context.
	Metadata *RequestMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`

	// RequestId is a unique identifier for this request.
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
}

func (x *ExecuteRequest) String() string {
	return fmt.Sprintf("ExecuteRequest{ToolName:%q, RequestId:%q}", x.ToolName, x.RequestId)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteRequest) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// GetParametersMap decodes the parameters bytes as a map.
func (x *ExecuteRequest) GetParametersMap() (map[string]interface{}, error) {
	if x == nil || len(x.Parameters) == 0 {
		return make(map[string]interface{}), nil
	}
	var params map[string]interface{}
	if err := json.Unmarshal(x.Parameters, &params); err != nil {
		return nil, err
	}
	return params, nil
}

func (x *ExecuteRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// PolicyDecision contains details about the policy evaluation.
type PolicyDecision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Decision is the policy verdict (allow/deny).
	Decision string `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`

	// PolicyName is the name of the policy that was evaluated.
	PolicyName string `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`

	// MatchedRule describes which rule matched.
	MatchedRule string `protobuf:"bytes,3,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"`

	// EvaluationTimeNs is the time taken to evaluate in nanoseconds.
	EvaluationTimeNs int64 `protobuf:"varint,4,opt,name=evaluation_time_ns,json=evaluationTimeNs,proto3" json:"evaluation_time_ns,omitempty"`

	// CacheHit indicates whether the decision was from cache.
	CacheHit bool `protobuf:"varint,5,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
}

func (x *PolicyDecision) Reset() {
	*x = PolicyDecision{}
}

func (x *PolicyDecision) String() string {
	return fmt.Sprintf("PolicyDecision{Decision:%q, PolicyName:%q, CacheHit:%v}", x.Decision, x.PolicyName, x.CacheHit)
}

func (*PolicyDecision) ProtoMessage() {}

func (x *PolicyDecision) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *PolicyDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *PolicyDecision) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyDecision) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

func (x *PolicyDecision) GetEvaluationTimeNs() int64 {
	if x != nil {
		return x.EvaluationTimeNs
	}
	return 0
}

func (x *PolicyDecision) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

// ExecuteResponse contains the result of a tool execution.
type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Result contains the tool execution result as JSON-encoded bytes.
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`

	// Error contains any error message.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`

	// Status indicates the outcome of the request.
	Status ExecutionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=agents.sandbox.v1alpha1.ExecutionStatus" json:"status,omitempty"`

	// RequestId echoes the request ID for correlation.
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`

	// PolicyDecision contains details about the policy evaluation.
	PolicyDecision *PolicyDecision `protobuf:"bytes,5,opt,name=policy_decision,json=policyDecision,proto3" json:"policy_decision,omitempty"`
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
}

func (x *ExecuteResponse) String() string {
	return fmt.Sprintf("ExecuteResponse{Status:%v, RequestId:%q, Error:%q}", x.Status, x.RequestId, x.Error)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecuteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteResponse) GetPolicyDecision() *PolicyDecision {
	if x != nil {
		return x.PolicyDecision
	}
	return nil
}
